version: '3'

dotenv: ['.env']

tasks:
  default:
    deps: [check]

  check:
    cmds:
      - shellcheck -x ./bin/dosapp ./install.sh
  install:
    cmds:
      - if [ -f ~/.local/bin/dosapp ]; then rm ~/.local/bin/dosapp; fi
      - ln -s "$(pwd)/bin/dosapp" ~/.local/bin/dosapp
