version: '3'

dotenv: ['.env']

tasks:
  default:
    deps: [check]

  check:
    cmds:
      - shellcheck -x ./bin/dosapp ./install.sh

  start:
    cmds:
      - PATH="$(pwd)/bin:${PATH}" ./bin/dosapp
