version: '3'

dotenv: ['.env']

tasks:
  default:
    deps: [check]

  lint:
    cmds:
      - shellcheck -x ./install.sh
      - go vet .
      - yamlfmt -lint '**/*.yml'

  format:
    cmds:
      - find . -name '*.go' -exec go fmt '{}' ';'
      - yamlfmt '**/*.yml'

  install:
    cmds:
      - go install .

  start:
    cmds:
      - go run .
