version: '3'

dotenv: ['.env']

tasks:
  default:
    deps: [check]

  check:
    cmds:
      - shellcheck -x ./install.sh
      - go vet .

  format:
    cmds:
      - find . -name '*.go' -exec go fmt '{}' ';'

  install:
    cmds:
      - go install .

  start:
    cmds:
      - go run .
