version: '3'

tasks:
  init:
    cmds:
      - mkdir -p "${DOSAPP_DISK_HOME}/wordperfect"
      - mkdir -p "${DOSAPP_CONFIG_HOME}/apps/wordperfect"
      - gomplate -i "$(cat "${DOSAPP_PACKAGE_HOME}/wordperfect/main.conf.tmpl")" > "${DOSAPP_CONFIG_HOME}/apps/wordperfect/main.conf"
      - gomplate -i "$(cat "${DOSAPP_PACKAGE_HOME}/wordperfect/install.conf.tmpl")" > "${DOSAPP_CONFIG_HOME}/apps/wordperfect/install.conf"
      - gomplate -i "$(cat "${DOSAPP_PACKAGE_HOME}/wordperfect/start.conf.tmpl")" > "${DOSAPP_CONFIG_HOME}/apps/wordperfect/start.conf"

  download:
    cmds:
      - if [ ! -f "${DOSAPP_DOWNLOAD_HOME}/wordperfect-6.2.7z" ]; then curl -L 'https://winworldpc.com/download/46c2a565-c3b5-18c3-9a11-c3a4e284a2ef/from/c39ac2af-c381-c2bf-1b25-11c3a4e284a2' -o "${DOSAPP_DOWNLOAD_HOME}/wordperfect-6.2.7z"; fi

  unpack:
    cmds:
      - rm -rf "${DOSAPP_DISK_HOME}/wordperfect/cdrom"
      - ${_7Z_BIN} x "${DOSAPP_DOWNLOAD_HOME}/wordperfect-6.2.7z" "-o${DOSAPP_DISK_HOME}/wordperfect/cdrom"

  install:
    deps: [download, unpack]
    cmds:
      - "${DOSBOX_BIN}" -userconf -conf "${DOSAPP_CONFIG_HOME}/main.conf" -conf "${DOSAPP_CONFIG_HOME}/apps/wordperfect/main.conf" -conf "${DOSAPP_CONFIG_HOME}/apps/wordperfect/install.conf"

  start:
    cmds:
      - "${DOSBOX_BIN}" -userconf -conf "${DOSAPP_CONFIG_HOME}/main.conf" -conf "${DOSAPP_CONFIG_HOME}/apps/wordperfect/main.conf" -conf "${DOSAPP_CONFIG_HOME}/apps/wordperfect/start.conf"
