version: '3'

dotenv: ['.env']

tasks:
  init:
    cmds:
      - mkdir -p "${DOSAPP_STATE_HOME}/apps/wordperfect"
      - mkdir -p "${DOSAPP_CONFIG_HOME}/apps/wordperfect"
      - mkdir -p "${DOSAPP_DOWNLOAD_HOME}"
      - 'if [ -n "${DOSAPP_DISK_A:-}" ]; then mkdir -p "${DOSAPP_DISK_A}"; fi'
      - 'if [ -n "${DOSAPP_DISK_B:-}" ]; then mkdir -p "${DOSAPP_DISK_B}"; fi'
      - 'if [ -n "${DOSAPP_DISK_C:-}" ]; then mkdir -p "${DOSAPP_DISK_C}"; else echo "DISAPP_DISK_C is required"; exit 1; fi'
      - '"${DOSAPP_BIN}" task template --package wordperfect main.conf.tmpl'
      - '"${DOSAPP_BIN}" task template --package wordperfect install.conf.tmpl'
      - '"${DOSAPP_BIN}" task template --package wordperfect start.conf.tmpl'

  download:
    cmds:
      - 'if [ ! -f "${DOSAPP_DOWNLOAD_HOME}/wordperfect-6.2.7z" ]; then curl -L "https://winworldpc.com/download/46c2a565-c3b5-18c3-9a11-c3a4e284a2ef/from/c39ac2af-c381-c2bf-1b25-11c3a4e284a2" -o "${DOSAPP_DOWNLOAD_HOME}/wordperfect-6.2.7z"; fi'

  unpack:
    deps: [download]
    cmds:
      - rm -rf "${DOSAPP_STATE_HOME}/apps/wordperfect/cdrom"
      - mkdir -p "${DOSAPP_STATE_HOME}/apps/wordperfect"
      - ${DOSAPP_7Z_BIN} x "${DOSAPP_DOWNLOAD_HOME}/wordperfect-6.2.7z" "-o${DOSAPP_STATE_HOME}/apps/wordperfect/cdrom"

  install:
    deps: [unpack]
    cmds:
      - '"${DOSAPP_DOSBOX_BIN}" -userconf -conf "${DOSAPP_CONFIG_HOME}/main.conf" -conf "${DOSAPP_CONFIG_HOME}/apps/wordperfect/main.conf" -conf "${DOSAPP_CONFIG_HOME}/apps/wordperfect/install.conf"'

  remove:
    cmds:
      - rm -rf "${DOSAPP_DISK_C}/COREL/WP62"
      - rm -rf "${DOSAPP_DISK_C}/COREL/WP62DOS"
      - 'echo "WARN: Not removing ${DOSAPP_DISK_C}/BTFONTS"'
      - 'echo "WARN: Not updating ${DOSAPP_DISK_C}/AUTOEXEC.BAT"'

  start:
    cmds:
      - '"${DOSAPP_DOSBOX_BIN}" -userconf -conf "${DOSAPP_CONFIG_HOME}/main.conf" -conf "${DOSAPP_CONFIG_HOME}/apps/wordperfect/main.conf" -conf "${DOSAPP_CONFIG_HOME}/apps/wordperfect/start.conf"'

  link:
    cmds:
      - '"${DOSAPP_BIN}" task template --link --package wordperfect bin/wp.tmpl'
      - chmod +x "${DOSAPP_LINK_HOME}/wp"

  unlink:
    cmds:
      - rm -f "${DOSAPP_LINK_HOME}/wp"
