# https://taskfile.dev

version: '3'

tasks:
  init:
    cmds:
      - '"${DOSAPP_BIN}" task template --config main.conf.tmpl'

  start:
    cmds:
      - '"${DOSAPP_DOSBOX_BIN}" -userconf -conf "${DOSAPP_CONFIG_HOME}/main.conf" -conf "${DOSAPP_CONFIG_HOME}//start.conf"'
