# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  init:
    cmds:
      - gomplate -i "$(cat "${DOSAPP_ROOT}/config/main.conf.tmpl")" > "${DOSAPP_CONFIG_HOME}/main.conf"
